name: DiscordVerify
version: '${project.version}'
main: de.netzkronehd.discordverifybot.DiscordVerifySpigot
author: NetzkroneHD
api-version: 1.13
softdepend:
  - PlaceholderAPI

commands:
  discordverify:
    aliases:
      - dcverify
      - verify
      - link
      - dclink
      - linkdiscord
      - linkdc
  discordverifyadmin:
    aliases:
      - dcverifyadmin
      - dcvadmin
      - dcva
permissions:
  discordverify.admin:
    default: op
    description: Permission to execute the admin command