name: DiscordVerify
version: '${project.version}'
main: de.netzkronehd.discordverifybot.DiscordVerifySpigot
api-version: 1.13
author: NetzkroneHD
softdepend:
  - PlaceholderAPI

commands:
  discordverify:
    aliases:
      - dcverify
      - verify
      - link
      - dclink
      - linkdiscord
      - linkdc